
server:
  servlet:
    context-path: /canalcliente

spring:
  datasource:
    url: jdbc:h2:mem:canalcliente
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    tags-sorter: 'alpha'
    operationsSorter: 'alpha'
    disable-swagger-default-url: true
    use-root-path: true
    doc-expansion: 'none'
  show-actuator: true
  writer-with-order-by-keys: true